### ISSUE TITLE
Transfer amount field bug

### ISSUE THREAD

**Issue by decentraliser** [nemfoundation/nem2-desktop-wallet#858] opened 2020-01-15 02:01 UTC
Sometimes, when inputting an amount, the amount field will get cleared

This happens when quickly inputting an amount just after the component is mounted
Also happens when quickly inputting an amount just after changing mosaic

Should be due to the validator.reset method (which is necessary)

**Comment by domakun** [comment] 2020-01-15 03:14
should allow user to set mosaic amount=0, because it's ok in rest 
![image](https://user-images.githubusercontent.com/34330538/72401807-24297c80-3788-11ea-92b9-3cadf1ccd4ea.png)

**Comment by decentraliser** [comment] 2020-01-15 03:19
please keed this comment from Jeff in mind if you do that
https://nem2.slack.com/archives/CME5PV744/p1575694003112800?thread_ts=1575628675.104500&cid=CME5PV744

**Comment by domakun** [comment] 2020-01-15 05:08
it's not caused by mounted, not sure where it is from, but fixed by set a default value of 0, and I set default mosaic to be nem.xem according to jeff's comment.

**Closed** 2020-01-21 10:46 UTC
Labels: bug, story-1
