### ISSUE TITLE
Wallet should support non-admin accounts on Windows

### ISSUE THREAD

**Issue by ryo-opening-line** [nemfoundation/nem2-desktop-wallet#839] opened 2020-01-12 11:17 UTC
1) It is not possible to install the program on Win10 with a non-admin account

2) Issue reported by @ryo-opening line
After creating a new account and relaunch nem2-wallet(0.8.11), I can no longer login nem2-wallet again....
the login dialog says "No wallet in local storage" as follows:

![image](https://user-images.githubusercontent.com/28587337/72217934-1d2c1f80-3578-11ea-9445-6445d63d8b7b.png)

- Steps To Reproduce
1. launch nem2-wallet(0.8.11)
2. create a new account
3. close new2-wallet
4. re-lauch nem2-wallet(0.8.11)
5. you can no longer login again....

- Environment
NEM2-Wallet: nem2-wallet-0.8.11.exe
OS: Windows10(build 18362.535)

**Comment by ryo-opening-line** [comment] 2020-01-12 23:44
i found a workaround.
it works fine when you run nem2-wallet as an administrator.
so it seems installer's issue related to privilege on windows.
could someone confirm it, please?

**Comment by decentraliser** [comment] 2020-01-13 00:43
very interesting, will try to reproduce it

**Comment by decentraliser** [comment] 2020-01-13 01:14
@ryo-opening-line on Win10:
Installed the program as admin
Log out, log in with a non-admin user
The wallet works fine

Uninstall the wallet with admin user
Login with non-admin user
I get an error message saying you must use an administrator account to install the program

So, could not reproduce this, but should be able to run the program as admin
@domakun @kaiyzen any idea about this?
It should be an issue with the build options

**Comment by domakun** [comment] 2020-01-13 01:55
I want to confirm one thing: When you created your account, did you create a wallet in your account? Because no wallet account will be cleared on the login page. @ryo-opening-line

**Comment by ryo-opening-line** [comment] 2020-01-13 03:12
@decentraliser @domakun thanks for confirming it!

@domakun yes. i created wallet in my account. i seems installer's issue on windows privilege:
the wallet might be able to read or write localStorage in windows on launching...

i tested the following steps again using different users:

1. remove %USERPROFILE%\AppData\Roaming\nem2-wallet-0.8.11
2. install nem2-wallet-0.8.11.exe
3. launch nem2-wallet-0.8.11
4. close nem2-wallet
5. re-launch nem2-wallet

the results are as follows:
- GOOD(installed as Admin and run As Admin)
- GOOD(installed as Admin and run As None Admin)
- GOOD(installed as None Admin and run As Admin)
- NOT GOOD(installed as None Admin and run as None Admin)

let me know if you need more information.

**Comment by domakun** [comment] 2020-01-13 09:03
@ryo-opening-line This bug is because we configured administrator permissions when packaging. I have modified the packaging file and will take effect in the next packaging version. Thank you for your feedback and help!

**Comment by domakun** [comment] 2020-01-13 09:05
![image](https://user-images.githubusercontent.com/34330538/72243370-bdd91880-3626-11ea-8cec-a244acb26e25.png)

**Comment by ryo-opening-line** [comment] 2020-01-13 09:12
@domakun thank you very much!  i really appreciate your fix.

**Comment by decentraliser** [comment] 2020-01-13 10:23
closing this one, will re-open if there is any similar issue with v0.8.12

**Comment by decentraliser** [comment] 2020-01-22 04:59
This should be fixed on 0.8.12, it works for me

@ryo-opening-line please re-open the issue if you still have issues!

**Closed** 2020-01-22 04:59 UTC
Labels: Under review, bug, priority, story-2
